name: ElXDa
options:
  bundleIdPrefix: com.vladimir
  deploymentTarget:
    iOS: "15.0"
targets:
  ElXDa:
    type: application
    platform: iOS
    sources:
      - path: ESP-BOX
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vladimir.esp
        MARKETING_VERSION: "0.1"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: ESP-BOX/Info.plist
